### ISSUE TITLE
Check and update 2013 and 2014 bibliography

### ISSUE THREAD

**Issue by JJ** [geneura/biblio#3]
I have found at least a paper by @amorag missing, but there might be others. Please check existing papers and add whatever is missing. We need it for the project reports.
Please take into account that the file is in UTF8, no funky business with Macs or if you update from the web.

**Comment by amorag** [comment]
I have included some missing ones (new and old) and fixed several accents and symbols.
There are some other remaining ones.
Maybe somebody could fix them 'automatically' somehow?

**Comment by pacastillo** [comment]
Fixed some symbols, fixed one of the papers in MAEB, and added the last one.
Everything has been done using gedit under Linux  ;)

**Comment by JJ** [comment]
:-)

2015-03-03 6:52 GMT+01:00 Pedro A. Castillo Valdivieso <
notifications@github.com>:

> Fixed some symbols, fixed one of the papers in MAEB, and added the last
> one.
> Everything has been done using gedit under Linux ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geneura/biblio/issues/3#issuecomment-76891281>.
>



-- 
JJ
